name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo ${{ github.repository }}
          echo ${{ github.owner }}
          echo "Hello World!"
