name: Playground workflow

on: 
  workflow_dispatch:
    inputs:
      country: 
        description: 'Country to greet'
        required: true
        
env:
  India: Namaste
  Japan: Sayonara
  England: Hello
jobs:
  test-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the caller
        env: 
          country: ${{ inputs.country }}
          greetMessage: '${{ env.country }}'
        run: |
          export myCountry=${{ format('{0}', env.country) }}
          export foo="${{ format('env.{0}', env.country) }}"
          echo ${{ env.country }}
          echo "${greetMessage}"
          echo "${foo}"
          echo "${env.India}"
        shell: bash
