name: hello-world
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Helm chart version to be installed
        type: string
        required: false
        default: $GITHUB_SHA
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: my-step
        run: |
          echo ${{ inputs.version }}
          echo ${{ github.repository_owner }}
          echo ${{ github.ref_name }}
          echo "Hello World!"
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo $shortSha
          echo "GIT_SHA_SHORT=$shortSha" >> $GITHUB_ENV
          echo "GIT_SHA_SHORT_NEW=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Query Git sha
        run:  echo ${{ env.GIT_SHA_SHORT_NEW }}
