name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo ${{ github.repository_owner }}
          echo ${{ github }}
          echo ${{ github.ref_name }}
          echo "Hello World!"
