name: Playground workflow

on: push
        
env:
  India: Namaste
  Japan: Sayonara
  England: Hello
jobs:
  test-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the caller
        env: 
          country: India
          greetMessage: ${{ env.country }}
        run: |
          export myCountry=${{ format('{0}', env.country) }}
          export foo="${{ format('env.{0}', env.country) }}"
          echo ${{ env.country }}
          echo ${{ greetMessage  }}
